#!/bin/bash

# Brings up the full OTLP receiver stack, configured by backends.conf:
#   1. validates the configuration
#   2. generates certificates (shared or dedicated, per backend)
#   3. writes the TLS config for every backend
#   4. provisions the Grafana datasources
#   5. starts all containers
#
# Which backends the agent exports to is a separate, agent-side step:
# run agent-config.sh - it only prints the otelConfig JSON.

set -euo pipefail
cd "$(dirname "$0")"

[[ -f backends.conf ]] || { echo "backends.conf is missing"; exit 1; }
# shellcheck source=backends.conf
source backends.conf

# uppercases a backend name and turns dashes into underscores: grafana-otel -> GRAFANA_OTEL
# (macOS ships bash 3.2, so ${var^^} is not an option)
backend_key() { printf '%s' "$1" | tr '[:lower:]-' '[:upper:]_'; }

# --- validate ----------------------------------------------------------------

for name in prometheus grafana-otel victoriametrics otelcol
do
  key=$(backend_key "$name")
  tls="${key}_TLS"
  case "${!tls:-none}" in
    none|tls|mtls) ;;
    *) echo "backends.conf: ${!tls} - ${tls} must be none, tls or mtls"; exit 1 ;;
  esac
  # victoriametrics runs unauthenticated locally, its TLS knob is none-only
  if [[ "$name" == "victoriametrics" && "${!tls:-none}" != "none" ]]; then
    echo "backends.conf: VICTORIAMETRICS_TLS must be none, TLS modes are covered by the other backends"
    exit 1
  fi
  certs="${key}_CERTS"
  case "${!certs:-shared}" in
    shared|dedicated) ;;
    *) echo "backends.conf: ${!certs} - ${certs} must be shared or dedicated"; exit 1 ;;
  esac
done

# --- certificates ------------------------------------------------------------

echo "Generating certificates..."
bash certs/create-certificates.sh
echo

# --- per-backend TLS configs ---------------------------------------------------

# basename of the server certificate a backend uses (shared or dedicated)
backend_cert() {
  local name=$1 key; key="$(backend_key "$name")_CERTS"
  [[ "${!key:-shared}" == "dedicated" ]] && { echo "$name"; return; }
  echo "server"
}

# web config for prometheus' HTTPS and client certificate settings
mkdir -p prometheus
cert="certs/$(backend_cert prometheus)"
{
  echo "# generated by quick-start.sh from backends.conf (PROMETHEUS_TLS=${PROMETHEUS_TLS:-none})"
  if [[ "${PROMETHEUS_TLS:-none}" != "none" ]]; then
    echo "tls_server_config:"
    echo "  cert_file: /${cert}.crt"
    echo "  key_file: /${cert}.key"
    if [[ "${PROMETHEUS_TLS:-none}" == "mtls" ]]; then
      echo "  client_auth_type: RequireAndVerifyClientCert"
      echo "  client_ca_file: /certs/ca.crt"
    fi
  fi
} > prometheus/web-config.yml

# collector config for the grafana-otel OTLP receiver
cert="certs/$(backend_cert grafana-otel)"
tls_block=""
if [[ "${GRAFANA_OTEL_TLS:-none}" != "none" ]]; then
  tls_block="        tls:
          cert_file: /${cert}.crt
          key_file: /${cert}.key"
  [[ "${GRAFANA_OTEL_TLS:-none}" == "mtls" ]] && tls_block+=$'\n          client_ca_file: /certs/ca.crt'
fi
cat > otel-collector.yaml <<EOF
# generated by quick-start.sh from backends.conf (GRAFANA_OTEL_TLS=${GRAFANA_OTEL_TLS:-none})

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
${tls_block}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/ready"

processors:
  batch:

exporters:
  otlp_http/metrics:
    endpoint: http://127.0.0.1:9090/api/v1/otlp
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/metrics]
EOF

# --- grafana datasources -------------------------------------------------------

mkdir -p grafana/provisioning/datasources
# fingerprint the CA - grafana re-provisions when this file changes, which is
# what makes the __file references below re-read rotated certificates
ca_fp=$(openssl x509 -in certs/ca.crt -noout -fingerprint -sha256 2>/dev/null || true)
{
  echo "# generated by quick-start.sh, one datasource per queryable backend"
  [[ -n "$ca_fp" ]] && echo "# $ca_fp"
  echo "apiVersion: 1"
  echo "datasources:"
  echo "  - name: prometheus"
  echo "    uid: prometheus"
  echo "    type: prometheus"
  echo "    access: proxy"
  echo "    isDefault: true"
  if [[ "${PROMETHEUS_TLS:-none}" == "none" ]]; then
    echo "    url: http://prometheus:9090"
  else
    echo "    url: https://prometheus:9090"
    echo "    jsonData:"
    echo "      tlsAuthWithCACert: true"
    [[ "${PROMETHEUS_TLS:-none}" == "mtls" ]] && echo "      tlsAuth: true"
    echo "    secureJsonData:"
    # file provider - the certs are mounted into the container at /certs, so a
    # cert rotation is picked up by a plain grafana restart
    echo "      tlsCACert: \$__file{/certs/ca.crt}"
    if [[ "${PROMETHEUS_TLS:-none}" == "mtls" ]]; then
      echo "      tlsClientCert: \$__file{/certs/client.crt}"
      echo "      tlsClientKey: \$__file{/certs/client.key}"
    fi
  fi
  # the internal prometheus of the grafana-otel container has no TLS of its own,
  # its certificate protects the OTLP ingest on port 4318
  echo "  - name: grafana-otel"
  echo "    uid: grafana-otel"
  echo "    type: prometheus"
  echo "    access: proxy"
  echo "    url: http://grafana-otel:9090"
  # victoriametrics speaks the prometheus querying API - the same panels work on it
  echo "  - name: victoriametrics"
  echo "    uid: victoriametrics"
  echo "    type: prometheus"
  echo "    access: proxy"
  echo "    url: http://victoriametrics:8428"
} > grafana/provisioning/datasources/datasources.yml


# collector config: OTLP in, fan-out to all three backends out
mkdir -p otelcol
cert="certs/$(backend_cert otelcol)"

{
  echo "# generated by quick-start.sh - receives the agent's OTLP and forwards to all backends"
  echo "receivers:"
  echo "  otlp:"
  echo "    protocols:"
  echo "      grpc:"
  echo "        endpoint: 0.0.0.0:4317"
  if [[ "${COLLECTOR_TLS:-none}" != "none" ]]; then
    echo "        tls:"
    echo "          cert_file: /${cert}.crt"
    echo "          key_file: /${cert}.key"
    [[ "${COLLECTOR_TLS:-none}" == "mtls" ]] && echo "          client_ca_file: /certs/ca.crt"
  fi
  echo "      http:"
  echo "        endpoint: 0.0.0.0:4318"
  if [[ "${COLLECTOR_TLS:-none}" != "none" ]]; then
    echo "        tls:"
    echo "          cert_file: /${cert}.crt"
    echo "          key_file: /${cert}.key"
    [[ "${COLLECTOR_TLS:-none}" == "mtls" ]] && echo "          client_ca_file: /certs/ca.crt"
  fi
  echo
  echo "exporters:"
  echo "  otlphttp/prometheus:"
  echo "    endpoint: https://prometheus:9090/api/v1/otlp"
  echo "    tls:"
  echo "      ca_file: /certs/ca.crt"
  if [[ "${PROMETHEUS_TLS:-none}" == "mtls" ]]; then
    echo "      cert_file: /certs/client.crt"
    echo "      key_file: /certs/client.key"
  fi
  echo "  otlphttp/grafana-otel:"
  echo "    endpoint: https://grafana-otel:4318"
  echo "    tls:"
  echo "      ca_file: /certs/ca.crt"
  if [[ "${GRAFANA_OTEL_TLS:-none}" == "mtls" ]]; then
    echo "      cert_file: /certs/client.crt"
    echo "      key_file: /certs/client.key"
  fi
  echo "  otlphttp/victoriametrics:"
  echo "    endpoint: http://victoriametrics:8428/opentelemetry"
  echo
  echo "service:"
  echo "  pipelines:"
  echo "    metrics:"
  echo "      receivers: [otlp]"
  echo "      exporters: [otlphttp/prometheus, otlphttp/grafana-otel, otlphttp/victoriametrics]"
} > otelcol/collector.yaml

# regenerate the diff dashboard from the main dashboard so they never drift
python3 gen-diff-dashboard.py

# --- start the stack -----------------------------------------------------------

echo "Starting containers..."
stack_existed=false
[[ -n "$(docker compose ps -q)" ]] && stack_existed=true
docker compose up -d
# mounted config files are only re-read on restart, a fresh stack does not need it
if [[ "$stack_existed" == "true" ]]; then
  docker compose restart
fi
echo

echo "=== OTLP Receiver Stack Up ==="
echo
echo "Grafana:        http://localhost:3000 (admin / admin, change on first login)"
echo "Prometheus:     https://localhost:9090 (TLS ${PROMETHEUS_TLS:-none}, browsing it needs the client certificate in your browser)"
echo "Grafana OTLP:   https://localhost:4320 (TLS ${GRAFANA_OTEL_TLS:-none})"
echo "VictoriaMetrics: http://localhost:8428 (OTLP at /opentelemetry/v1/metrics + the prometheus querying API)"
echo "Collector:      https://localhost:4322 (TLS ${COLLECTOR_TLS:-none}, fans out to all three backends)"
echo
echo "All backends are running and visible in Grafana."
echo "To pick what the agent exports to, run: bash agent-config.sh"
echo "It prints the otelConfig JSON for the monitoring agent, docker stays untouched."
echo
echo "To stop: docker compose down    To wipe data: docker compose down -v"
